### ISSUE TITLE
Read-only clone of MGV fails

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitver_oldie#19]
When trying to clone the project readonly on a machine without ssh access I noticed, that this is currently not possible. I used the `git config --set url.<base>.insteadof=<old-base>` mechanism to get it working. But it should be possible without doing anything to get a full readonly clone. This is probably an acceptance factor.

Can we change the fetch url in the submodules file for each submodule to `https://...`? The alternative is changing the url on every submodule and define the ssh push url manually once for each sm.

**Comment by scunz** [comment]
Sorry for the late reply, but you're of course right. Actually, I don't have ssh access to GitHub since August. But due to my experience, it was an absolute natural thing for me to issue a global config like the one you showed above. However, I do realize that this wasn't the best solution for everyone. Actually, another reason was to not hide away the fact that libgit2 didn't support SSH at that time. libgit2 does that now (but I think given the way we compile[1] it, we do not yet - See my comments in the interesting PR numbered 2002 in libgit2...)

**So, please go ahead and change the `.gitmodules` to only contain `https://` based urls.**

[1] Though, this is another issue, but: Once libgit2 hits a stable release, we should switch back to compile it via it's own scripts and bug them with PRs until these scripts do what is required in the "real world"...

**Comment by antis81** [comment]
Ok, should be done. :ok:

**Comment by scunz** [comment]
Actually, it was almost done. Needs an update to the submodule entries in `MacGitver.git`, so that a fresh checkout of mgv knows about the right version of `libGitWrap`'s `.gitmodules` :)

Will commit that soonish :)
