### ISSUE TITLE
Do we care for Windows XP and earlier?

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitver_oldie#9]
@antis81, Russell Belfer just announced in libgit2/libgit2#1806 that `libgit2` will drop thread-support for Windows XP and earlier. Our `GitWrap` library requires the underlying libgit2 to be somewhat thread safe, since we do stuff in worker threads.

Do we care for Windows XP and earlier? If so, will we invent special handling in GitWrap in a way that "we won't assume the underlying stuff is thread safe"?

In my opinion, there are only 3 stable versions of Windows that are worth to support, anyway: 3.11, 5.0 and 7.0.

I don't think 3.11 has a large user base nowadays and we cannot support it because of Qt. For the other 2, I personally would like to support them (in whatever way).

**Comment by antis81** [comment]
Yeah somewhat up and running again :+1:. Good to know that libgit2 does not support WXP anymore. I personally don't have any version of windows, but as we target multiple platforms we should think about supporting that. I tried several times, but I couldn't manage compiling MGV on any windows around. Maybe I should start thinking about cross compiling.

Even nowadays a lot of people are still using WXP as a professional development platform. So support is likely to be requested. But I personally don't like to put extra effort into that.

Btw.: Most of the Qt4 stuff runs on old OS/2, so it might even be running on 3.11, but I bet you're right, because this is 16 bit stuff. If something's worth to support for nostalgic reasons, then let's dig out the good old C64 and support Contiki OS - just because it's cool :smile:.

Anyways, I think we should focus on getting some packaging mechanisms running to release MGV as a download. We started that roughly some time ago, but didn't work on that any further in favor to features and basic structure. This is all there in most parts now, so we can go on with the packaging. @claus007 Do you like doing the homepage stuff? There's some drafts existing and a domain, e-mail addresses etc. But in an early state - just like MGV itself :smile:.

**Comment by arrbee** [comment]
> Good to know that libgit2 does not support WXP anymore

Just to clarify, libgit2 will continue to support XP; we just want to drop support for our "THREADSAFE" compile option that enables various internal mutexes for thread safety. Using libgit2 without threads will still work.

**Comment by scunz** [comment]
@antis81, okay, So we probably should ignore the issue on our side totally. As discussion progresses on the libgit2 side, it looks like the GitHub-For-Windows guys are also depending on Windows XP - which probably translates to: "They will find a solution for the issue whatsoever" :-)

The remainder of your comment should probably move to issues on their own. But I'll give short answers here anyway:
- First of all, nice to see you "up and running" again. Same for me; though most of the services on my servers have now different ports due to the firewalled public hostel WiFi... If you want to push sth to our gl mirrors, push it to port 143 (Insecure IMAP) :-)
- Qt + C64 sound, well, interesting. Do you know how to put ICU's 26 MiB Unicode tables onto 360 KiB floppy discs? :cow: "Insert disc 65 to get your error message!"
- Compiling MGV on Windows is straight forward: Qt4 or Qt5 + CMake + any version of MSVC should do (I personally own a MSVC 2008 Prof, but I also compiled it with MSVC2010 Express).
- As for the packaging: Uhm, I had redistributable packages done for Linux, Mac and Windows.
- And wrt to HomePage: We should open up another issue on that one.
